stages:
  - verify

.default-python-job: &default-python-job
  image: python:3.13
  only:
    - branches
    - merge_requests
  cache:
    key: shared-pip-cache
    paths:
      - .cache/pip
    policy: pull-push
  before_script:
    - pip config set global.cache-dir .cache/pip
    - pip install --upgrade pip
    - pip install -r requirements.txt

pyright-check:
  <<: *default-python-job
  stage: verify
  allow_failure: true
  script:
    - pip install pyright
    - pyright .

lint-check:
  <<: *default-python-job
  stage: verify
  script:
    - pip install ruff
    - ruff check .

format-check:
  <<: *default-python-job
  stage: verify
  script:
    - pip install ruff
    - ruff format --check --diff .

security-check:
  <<: *default-python-job
  stage: verify
  script:
    - pip install bandit
    - bandit -r . -c pyproject.toml

markdown-check:
  stage: verify
  image: node:latest
  only:
    - branches
    - merge_requests
  script:
    - npm install --global markdownlint-cli
    - markdownlint '**/*.md'
