variables:
  compare_branch: dev-v0.2.0
  GIT_DEPTH: 0
  kivy_stubs_repo: https://github.com/ScarlettSamantha/python-kivy-stubs.git
  panda3d_stubs_repo: https://github.com/WMOkiishi/types-panda3d.git
  direct_stubs_repo: https://git.scarlettbytes.nl/scarlett/direct-stubs.git

stages:
  - verify
  - package

.default-python-job: &default-python-job
  image: python:3.13
  only:
    - branches
    - merge_requests
  cache:
    key: shared-pip-cache
    paths:
      - .cache/pip
    policy: pull-push
  before_script:
    - pip config set global.cache-dir .cache/pip
    - pip install --upgrade pip --root-user-action=ignore
    - pip install -r requirements.txt --root-user-action=ignore
    - git clone --depth 1 $panda3d_stubs_repo stubs/panda3d
    - git clone --depth 1 $kivy_stubs_repo stubs/kivy
    - git clone --depth 1 $direct_stubs_repo stubs/direct
  
pyright-full-check:
  <<: *default-python-job
  stage: verify
  allow_failure: true
  only:
    - merge_requests
  script:
    - pip install pyright --root-user-action=ignore
    - pyright . -p pyrightconfig.json

pyright-diff-check:
  <<: *default-python-job
  stage: verify
  except:
    - merge_requests
  script:
    - pip install pyright --root-user-action=ignore
    - git fetch origin $compare_branch
    - |
      changed_files=$(git diff --diff-filter=ACMR --name-only origin/$compare_branch...HEAD -- '*.py')
      if [ -n "$changed_files" ]; then
        echo "Changed Python files:"
        echo "$changed_files"
        pyright $changed_files -p pyrightconfig.json
      else
        echo "No Python files changed. Skipping pyright."
      fi

lint-check:
  <<: *default-python-job
  stage: verify
  script:
    - pip install ruff --root-user-action=ignore
    - ruff check .

format-check:
  <<: *default-python-job
  stage: verify
  script:
    - pip install ruff --root-user-action=ignore
    - ruff format --check --diff .

security-check:
  <<: *default-python-job
  stage: verify
  script:
    - pip install bandit --root-user-action=ignore
    - bandit -r . -c pyproject.toml

markdown-check:
  <<: *default-python-job
  stage: verify
  only:
    - branches
    - merge_requests
  script:
    - pymarkdownlnt --config .markdownlnt.json scan '**/*.md'

package-linux:
  <<: *default-python-job
  inherit: {}
  stage: package
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: manual
    - when: never
  script:
    - pip install briefcase --root-user-action=ignore
    - briefcase update -r
    - briefcase update
    - briefcase build linux
    - briefcase package linux
    - mkdir -p builds
    - cp dist/*.deb builds/
  artifacts:
    paths:
      - builds/*.deb
    expire_in: 1 week
