[tool.briefcase]
project_name = "SCiv"
version = "0.1.5"
package = "nl.scarlettbytes.sciv"
bundle = "nl.scarlettbytes.sciv"

[tool.briefcase.app.sciv]
assets = [
  "assets",
  "exceptions",
  "gameplay",
  "helpers",
  "i18n",
  "managers",
  "menus",
  "mixins",
  "system",
  "world",
]
formal_name = "Sciv"
description = "An open-source Civ-like game"
long_description = "A Python project for Civ-like game made in panda3d."
sources = ["sciv"]
distributions = ["appdir"]
bundle = "nl.scarlettbytes.sciv"
entry_point = "main:main"
license.file = "LICENSE"
requires = [
  "panda3d",
  "panda3d_kivy",
  "noise",
  "webcolors",
  "python-dotenv",
  "sentry-sdk",
  "numpy",
  "panda3d-simplepbr",
  "pillow",
  "panda3d-gltf",
  "dill",
  "dill[graph]",
  "py_trees",
  "Pmw",
  "rich",
  "graphviz",
  "matplotlib",
  "gprof2dot",
]

[tool.poetry]
authors = ["Scarlett Samantha Verheul <scarlett.verheul@gmail.com>"]
dependencies.python = "^3.12"
description = "A Python project for Civ-like game"
license = "MIT"
name = "SCiv"

[tool.ruff]
ignore = ["E501", "F841", "E721", "E402"]
line-length = 120
select = ["E", "W", "F"]
exclude = ["**/stubs", "**/.pyenv", "**/site-packages", "**/*.pyi"]

[tool.pydocstyle]
add-ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107"]
ignore = ["system/subsystems/"]

[tool.pyright]
typeCheckingMode = "strict"
exclude = [
  "**/stubs",
  "**/site-packages",
  "**/*.pyi",
  "sciv/system/subsystems/hexgen/",
]
stubPath = "./typings"
pythonPlatform = "Linux"


[tool.bandit]
skips = ["B311", "B301", "B101", "B403"]

[tool.semantic_release]
changelog_function = "changelog.py:openciv_changelog"
commit_parser = "emoji"
github_release = false
version_source = "commit"
version_variables = ["version.py:__version__"]

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"
template_dir = "templates"

[tool.semantic_release.commit_parser_options]
major_tags = [":boom:"]
minor_tags = [
  ":sparkles:",
  ":children_crossing:",
  ":lipstick:",
  ":iphone:",
  ":egg:",
  ":chart_with_upwards_trend:",
]
patch_tags = [
  ":ambulance:",
  ":lock:",
  ":bug:",
  ":zap:",
  ":goal_net:",
  ":alien:",
  ":wheelchair:",
  ":speech_balloon:",
  ":mag:",
  ":apple:",
  ":penguin:",
  ":checkered_flag:",
  ":robot:",
  ":green_apple:",
]

[tool.pymarkdownlnt]
log.level = "INFO"
log.stack-trace = true
rules = ["MD013"]
