"""
This type stub file was generated by pyright.
"""

"""
to run this test suite, first build and install `dill`.

  $ python -m pip install ../..


then run the tests with:

  $ python -m dill.tests


or, if `nose` is installed:

  $ nosetests  

"""
