"""
This type stub file was generated by pyright.
"""

import builtins

"""
Module to show if an object has changed since it was memorised
"""
HAS_NUMPY = ...
getrefcount = ...
memo = ...
id_to_obj = ...
builtins_types = ...
dont_memo = ...
def get_attrs(obj): # -> Any | None:
    """
    Gets all the attributes of an object though its __dict__ or return None
    """
    ...

def get_seq(obj, cache=...): # -> list[Any] | None:
    """
    Gets all the items in a sequence or return None
    """
    ...

def memorise(obj, force=...): # -> None:
    """
    Adds an object to the memo, and recursively adds all the objects
    attributes, and if it is a container, its items. Use force=True to update
    an object already in the memo. Updating is not recursively done.
    """
    ...

def release_gone(): # -> None:
    ...

def whats_changed(obj, seen=..., simple=..., first=...): # -> bool | dict[Any, None] | tuple[dict[Any, None], bool]:
    """
    Check an object against the memo. Returns a list in the form
    (attribute changes, container changed). Attribute changes is a dict of
    attribute name to attribute value. container changed is a boolean.
    If simple is true, just returns a boolean. None for either item means
    that it has not been checked yet
    """
    ...

def has_changed(*args, **kwds): # -> bool | dict[Any, None] | tuple[dict[Any, None], bool]:
    ...

__import__ = ...
if hasattr(builtins, "_"):
    ...
