"""
This type stub file was generated by pyright.
"""

from .__info__ import __author__, __doc__, __license__, __version__
from ._dill import CONTENTS_FMODE, DEFAULT_PROTOCOL, FILE_FMODE, HANDLE_FMODE, HIGHEST_PROTOCOL, PickleError, PickleWarning, Pickler, PicklingError, PicklingWarning, Unpickler, UnpicklingError, UnpicklingWarning, check, copy, dump, dumps, load, loads, pickle, pickles, register
from .session import dump_module, dump_session, load_module, load_module_asdict, load_session
from . import detect, logger, objtypes as types, session, source, temp
from .settings import settings

objects = ...
def load_types(pickleable=..., unpickleable=...): # -> None:
    """load pickleable and/or unpickleable types to ``dill.types``

    ``dill.types`` is meant to mimic the ``types`` module, providing a
    registry of object types.  By default, the module is empty (for import
    speed purposes). Use the ``load_types`` function to load selected object
    types to the ``dill.types`` module.

    Args:
        pickleable (bool, default=True): if True, load pickleable types.
        unpickleable (bool, default=True): if True, load unpickleable types.

    Returns:
        None
    """
    ...

def extend(use_dill=...): # -> None:
    '''add (or remove) dill types to/from the pickle registry

    by default, ``dill`` populates its types to ``pickle.Pickler.dispatch``.
    Thus, all ``dill`` types are available upon calling ``'import pickle'``.
    To drop all ``dill`` types from the ``pickle`` dispatch, *use_dill=False*.

    Args:
        use_dill (bool, default=True): if True, extend the dispatch table.

    Returns:
        None
    '''
    ...

def license(): # -> None:
    """print license"""
    ...

def citation(): # -> None:
    """print citation"""
    ...

