"""
This type stub file was generated by pyright.
"""

import sys
import abc
import dataclasses
import importlib.machinery
import ctypes
import typing
from pickle import PickleError, PicklingError, Unpickler as StockUnpickler, UnpicklingError, _Pickler as StockPickler
from _thread import LockType, RLock as RLockType, _ThreadHandle as ThreadHandleType
from types import ClassMethodDescriptorType, CodeType, FunctionType, GetSetDescriptorType, MappingProxyType as DictProxyType, MemberDescriptorType, MethodDescriptorType, MethodType, ModuleType, WrapperDescriptorType
from weakref import CallableProxyType, ProxyType, ReferenceType
from functools import _lru_cache_wrapper as LRUCacheType

"""
dill: a utility for serialization of python objects

The primary functions in `dill` are :func:`dump` and
:func:`dumps` for serialization ("pickling") to a
file or to a string, respectively, and :func:`load`
and :func:`loads` for deserialization ("unpickling"),
similarly, from a file or from a string. Other notable
functions are :func:`~dill.dump_module` and
:func:`~dill.load_module`, which are used to save and
restore module objects, including an intepreter session.

Based on code written by Oren Tirosh and Armin Ronacher.
Extended to a (near) full set of the builtin types (in types module),
and coded to the pickle interface, by <mmckerns@caltech.edu>.
Initial port to python3 by Jonathan Dobson, continued by mmckerns.
Tested against "all" python types (Std. Lib. CH 1-15 @ 2.7) by mmckerns.
Tested against CH16+ Std. Lib. ... TBD.
"""
__all__ = ['dump', 'dumps', 'load', 'loads', 'copy', 'Pickler', 'Unpickler', 'register', 'pickle', 'pickles', 'check', 'DEFAULT_PROTOCOL', 'HIGHEST_PROTOCOL', 'HANDLE_FMODE', 'CONTENTS_FMODE', 'FILE_FMODE', 'PickleError', 'PickleWarning', 'PicklingError', 'PicklingWarning', 'UnpicklingError', 'UnpicklingWarning']
__module__ = ...
log = ...
diff = ...
_use_diff = ...
OLD38 = ...
OLD39 = ...
OLD310 = ...
OLD312a7 = ...
BufferType = memoryview
ClassType = type
EllipsisType = ...
NotImplementedType = ...
SliceType = slice
TypeType = type
XRangeType = range
GENERATOR_FAIL = ...
EXTENSION_SUFFIXES = ...
HAS_CTYPES = ...
IS_PYPY = ...
NumpyUfuncType = ...
NumpyDType = ...
NumpyArrayType = ...
if not importlib.machinery.PathFinder().find_spec('numpy'):
    ...
NumpyUfuncType = ...
NumpyDType = ...
NumpyArrayType = ...
def __hook__(): # -> Literal[True]:
    ...

if NumpyArrayType:
    def ndarraysubclassinstance(obj_type): # -> bool:
        ...
    
    def numpyufunc(obj_type): # -> bool:
        ...
    
    def numpydtype(obj_type): # -> bool:
        ...
    
else:
    def ndarraysubclassinstance(obj): # -> Literal[False]:
        ...
    
    def numpyufunc(obj): # -> Literal[False]:
        ...
    
    def numpydtype(obj): # -> Literal[False]:
        ...
    
CellType = ...
PartialType = ...
SuperType = ...
ItemGetterType = ...
AttrGetterType = ...
if not isinstance(LRUCacheType, type):
    LRUCacheType = ...
def get_file_type(*args, **kwargs): # -> type[Any]:
    ...

IS_PYODIDE = ...
FileType = ...
TextWrapperType = ...
BufferedRandomType = ...
BufferedReaderType = ...
BufferedWriterType = ...
PyTextWrapperType = ...
PyBufferedRandomType = ...
PyBufferedReaderType = ...
PyBufferedWriterType = ...
OutputType = ...
IS_IPYTHON = ...
ExitType = ...
IPYTHON_SINGLETONS = ...
class Sentinel:
    """
    Create a unique sentinel object that is pickled as a constant.
    """
    def __init__(self, name, module_name=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __copy__(self): # -> Self:
        ...
    
    def __deepcopy__(self, memo): # -> Self:
        ...
    
    def __reduce__(self): # -> Any:
        ...
    
    def __reduce_ex__(self, protocol): # -> Any:
        ...
    


HANDLE_FMODE = ...
CONTENTS_FMODE = ...
FILE_FMODE = ...
def copy(obj, *args, **kwds): # -> Any:
    """
    Use pickling to 'copy' an object (i.e. `loads(dumps(obj))`).

    See :func:`dumps` and :func:`loads` for keyword arguments.
    """
    ...

def dump(obj, file, protocol=..., byref=..., fmode=..., recurse=..., **kwds): # -> None:
    """
    Pickle an object to a file.

    See :func:`dumps` for keyword arguments.
    """
    ...

def dumps(obj, protocol=..., byref=..., fmode=..., recurse=..., **kwds): # -> bytes:
    """
    Pickle an object to a string.

    *protocol* is the pickler protocol, as defined for Python *pickle*.

    If *byref=True*, then dill behaves a lot more like pickle as certain
    objects (like modules) are pickled by reference as opposed to attempting
    to pickle the object itself.

    If *recurse=True*, then objects referred to in the global dictionary
    are recursively traced and pickled, instead of the default behavior
    of attempting to store the entire global dictionary. This is needed for
    functions defined via *exec()*.

    *fmode* (:const:`HANDLE_FMODE`, :const:`CONTENTS_FMODE`,
    or :const:`FILE_FMODE`) indicates how file handles will be pickled.
    For example, when pickling a data file handle for transfer to a remote
    compute service, *FILE_FMODE* will include the file contents in the
    pickle and cursor position so that a remote method can operate
    transparently on an object with an open file handle.

    Default values for keyword arguments can be set in :mod:`dill.settings`.
    """
    ...

def load(file, ignore=..., **kwds): # -> Any:
    """
    Unpickle an object from a file.

    See :func:`loads` for keyword arguments.
    """
    ...

def loads(str, ignore=..., **kwds): # -> Any:
    """
    Unpickle an object from a string.

    If *ignore=False* then objects whose class is defined in the module
    *__main__* are updated to reference the existing class in *__main__*,
    otherwise they are left to refer to the reconstructed type, which may
    be different.

    Default values for keyword arguments can be set in :mod:`dill.settings`.
    """
    ...

class MetaCatchingDict(dict):
    def get(self, key, default=...): # -> None:
        ...
    
    def __missing__(self, key): # -> Callable[..., None]:
        ...
    


class PickleWarning(Warning, PickleError):
    ...


class PicklingWarning(PickleWarning, PicklingError):
    ...


class UnpicklingWarning(PickleWarning, UnpicklingError):
    ...


class Pickler(StockPickler):
    """python's Pickler extended to interpreter sessions"""
    dispatch: typing.Dict[type, typing.Callable[[Pickler, typing.Any], None]] = ...
    _session = ...
    def __init__(self, file, *args, **kwds) -> None:
        ...
    
    def save(self, obj, save_persistent_id=...): # -> None:
        ...
    
    def dump(self, obj): # -> None:
        ...
    


class Unpickler(StockUnpickler):
    """python's Unpickler extended to interpreter sessions and more types"""
    _session = ...
    def find_class(self, module, name): # -> dict[str, Any] | type[None] | Any:
        ...
    
    def __init__(self, *args, **kwds) -> None:
        ...
    
    def load(self): # -> Any:
        ...
    


pickle_dispatch_copy = ...
def pickle(t, func): # -> None:
    """expose :attr:`~Pickler.dispatch` table for user-created extensions"""
    ...

def register(t): # -> Callable[..., Any]:
    """decorator to register types to Pickler's :attr:`~Pickler.dispatch` table"""
    ...

def use_diff(on=...): # -> None:
    """
    Reduces size of pickles by only including object which have changed.

    Decreases pickle size but increases CPU time needed.
    Also helps avoid some unpickleable objects.
    MUST be called at start of script, otherwise changes will not be recorded.
    """
    ...

_reverse_typemap = ...
if sys.hexversion < 50856098:
    ...
x = ...
_incedental_reverse_typemap = ...
if ExitType:
    ...
if InputType:
    ...
if sys.hexversion >= 51052720:
    ...
_incedental_types = ...
_typemap = ...
class match:
    """
    Make avaialable a limited structural pattern matching-like syntax for Python < 3.10

    Patterns can be only tuples (without types) currently.
    Inspired by the package pattern-matching-PEP634.

    Usage:
    >>> with match(args) as m:
    >>>     if   m.case(('x', 'y')):
    >>>         # use m.x and m.y
    >>>     elif m.case(('x', 'y', 'z')):
    >>>         # use m.x, m.y and m.z

    Equivalent native code for Python >= 3.10:
    >>> match args:
    >>>     case (x, y):
    >>>         # use x and y
    >>>     case (x, y, z):
    >>>         # use x, y and z
    """
    def __init__(self, value) -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *exc_info): # -> Literal[False]:
        ...
    
    def case(self, args): # -> bool:
        """just handles tuple patterns"""
        ...
    
    @property
    def fields(self): # -> dict[Any, Any]:
        ...
    
    def __getattr__(self, item):
        ...
    


ALL_CODE_PARAMS = ...
ENCODE_PARAMS = ...
if ThreadHandleType:
    ...
class _itemgetter_helper:
    def __init__(self) -> None:
        ...
    
    def __getitem__(self, item): # -> None:
        ...
    


class _attrgetter_helper:
    def __init__(self, attrs, index=...) -> None:
        ...
    
    def __getattribute__(self, attr): # -> Self:
        ...
    


class _dictproxy_helper(dict):
    def __ror__(self, a):
        ...
    


_dictproxy_helper_instance = ...
__d = ...
MAPPING_PROXY_TRICK = ...
_CELL_REF = ...
_CELL_EMPTY = ...
@register(CodeType)
def save_code(pickler, obj): # -> None:
    ...

@register(dict)
def save_module_dict(pickler, obj): # -> None:
    ...

if not OLD310 and MAPPING_PROXY_TRICK:
    def save_dict_view(dicttype): # -> list[tuple[str, Callable[..., None]]]:
        ...
    
else:
    def save_dict_view(dicttype): # -> tuple[tuple[str, Callable[..., None]], tuple[str, Callable[..., None]], tuple[str, Callable[..., None]]]:
        ...
    
@register(ClassType)
def save_classobj(pickler, obj): # -> None:
    ...

@register(typing._GenericAlias)
def save_generic_alias(pickler, obj): # -> None:
    ...

if ThreadHandleType:
    @register(ThreadHandleType)
    def save_thread_handle(pickler, obj): # -> None:
        ...
    
@register(LockType)
def save_lock(pickler, obj): # -> None:
    ...

@register(RLockType)
def save_rlock(pickler, obj): # -> None:
    ...

def save_socket(pickler, obj): # -> None:
    ...

@register(FileType)
@register(BufferedReaderType)
@register(BufferedWriterType)
@register(TextWrapperType)
def save_file(pickler, obj): # -> None:
    ...

if BufferedRandomType:
    @register(BufferedRandomType)
    def save_file(pickler, obj): # -> None:
        ...
    
if PyTextWrapperType:
    @register(PyBufferedReaderType)
    @register(PyBufferedWriterType)
    @register(PyTextWrapperType)
    def save_file(pickler, obj): # -> None:
        ...
    
if InputType:
    @register(InputType)
    def save_stringi(pickler, obj): # -> None:
        ...
    
    @register(OutputType)
    def save_stringo(pickler, obj): # -> None:
        ...
    
if LRUCacheType is not None:
    @register(LRUCacheType)
    def save_lru_cache(pickler, obj): # -> None:
        ...
    
@register(SuperType)
def save_super(pickler, obj): # -> None:
    ...

if IS_PYPY:
    @register(MethodType)
    def save_instancemethod0(pickler, obj): # -> None:
        ...
    
else:
    @register(MethodType)
    def save_instancemethod0(pickler, obj): # -> None:
        ...
    
if not IS_PYPY:
    @register(MemberDescriptorType)
    @register(GetSetDescriptorType)
    @register(MethodDescriptorType)
    @register(WrapperDescriptorType)
    @register(ClassMethodDescriptorType)
    def save_wrapper_descriptor(pickler, obj): # -> None:
        ...
    
else:
    @register(MemberDescriptorType)
    @register(GetSetDescriptorType)
    def save_wrapper_descriptor(pickler, obj): # -> None:
        ...
    
@register(CellType)
def save_cell(pickler, obj): # -> None:
    ...

if MAPPING_PROXY_TRICK:
    @register(DictProxyType)
    def save_dictproxy(pickler, obj): # -> None:
        ...
    
else:
    @register(DictProxyType)
    def save_dictproxy(pickler, obj): # -> None:
        ...
    
@register(SliceType)
def save_slice(pickler, obj): # -> None:
    ...

@register(XRangeType)
@register(EllipsisType)
@register(NotImplementedType)
def save_singleton(pickler, obj): # -> None:
    ...

@register(ReferenceType)
def save_weakref(pickler, obj): # -> None:
    ...

@register(ProxyType)
@register(CallableProxyType)
def save_weakproxy(pickler, obj): # -> None:
    ...

@register(ModuleType)
def save_module(pickler, obj): # -> None:
    ...

@register(TypeType)
def save_type(pickler, obj, postproc_list=...): # -> None:
    ...

@register(property)
@register(abc.abstractproperty)
def save_property(pickler, obj): # -> None:
    ...

@register(staticmethod)
@register(classmethod)
@register(abc.abstractstaticmethod)
@register(abc.abstractclassmethod)
def save_classmethod(pickler, obj): # -> None:
    ...

@register(FunctionType)
def save_function(pickler, obj):
    ...

if HAS_CTYPES and hasattr(ctypes, 'pythonapi'):
    _PyCapsule_New = ...
    _PyCapsule_GetPointer = ...
    _PyCapsule_GetDestructor = ...
    _PyCapsule_GetContext = ...
    _PyCapsule_GetName = ...
    _PyCapsule_IsValid = ...
    _PyCapsule_SetContext = ...
    _PyCapsule_SetDestructor = ...
    _PyCapsule_SetName = ...
    _PyCapsule_SetPointer = ...
    _testcapsule_name = ...
    _testcapsule = ...
    PyCapsuleType = ...
    @register(PyCapsuleType)
    def save_capsule(pickler, obj): # -> None:
        ...
    
else:
    _testcapsule = ...
if hasattr(dataclasses, "_HAS_DEFAULT_FACTORY_CLASS"):
    @register(dataclasses._HAS_DEFAULT_FACTORY_CLASS)
    def save_dataclasses_HAS_DEFAULT_FACTORY_CLASS(pickler, obj): # -> None:
        ...
    
if hasattr(dataclasses, "MISSING"):
    @register(type(dataclasses.MISSING))
    def save_dataclasses_MISSING_TYPE(pickler, obj): # -> None:
        ...
    
if hasattr(dataclasses, "KW_ONLY"):
    @register(type(dataclasses.KW_ONLY))
    def save_dataclasses_KW_ONLY_TYPE(pickler, obj): # -> None:
        ...
    
if hasattr(dataclasses, "_FIELD_BASE"):
    @register(dataclasses._FIELD_BASE)
    def save_dataclasses_FIELD_BASE(pickler, obj): # -> None:
        ...
    
def pickles(obj, exact=..., safe=..., **kwds): # -> bool:
    """
    Quick check if object pickles with dill.

    If *exact=True* then an equality test is done to check if the reconstructed
    object matches the original object.

    If *safe=True* then any exception will raised in copy signal that the
    object is not picklable, otherwise only pickling errors will be trapped.

    Additional keyword arguments are as :func:`dumps` and :func:`loads`.
    """
    ...

def check(obj, *args, **kwds): # -> None:
    """
    Check pickling of an object across another process.

    *python* is the path to the python interpreter (defaults to sys.executable)

    Set *verbose=True* to print the unpickled object in the other process.

    Additional keyword arguments are as :func:`dumps` and :func:`loads`.
    """
    ...

def is_dill(pickler, child=...): # -> bool:
    "check the dill-ness of your pickler"
    ...

