"""
This type stub file was generated by pyright.
"""

"""
Methods for detecting objects leading to pickling failures.
"""
__all__ = ['baditems', 'badobjects', 'badtypes', 'code', 'errors', 'freevars', 'getmodule', 'globalvars', 'nestedcode', 'nestedglobals', 'outermost', 'referredglobals', 'referrednested', 'trace', 'varnames']
def getmodule(object, _filename=..., force=...): # -> ModuleType | Any | None:
    """get the module of the object"""
    ...

def outermost(func): # -> Any | None:
    """get outermost enclosing object (i.e. the outer function in a closure)

    NOTE: this is the object-equivalent of getsource(func, enclosing=True)
    """
    ...

def nestedcode(func, recurse=...): # -> list[Any]:
    """get the code objects for any nested functions (e.g. in a closure)"""
    ...

def code(func): # -> CodeType | None:
    """get the code object for the given function or method

    NOTE: use dill.source.getsource(CODEOBJ) to get the source code
    """
    ...

def referrednested(func, recurse=...): # -> list[Any]:
    """get functions defined inside of func (e.g. inner functions in a closure)

    NOTE: results may differ if the function has been executed or not.
    If len(nestedcode(func)) > len(referrednested(func)), try calling func().
    If possible, python builds code objects, but delays building functions
    until func() is called.
    """
    ...

def freevars(func): # -> dict[Any, Any] | dict[str, Any]:
    """get objects defined in enclosing code that are referred to by func

    returns a dict of {name:object}"""
    ...

def nestedglobals(func, recurse=...): # -> list[Any]:
    """get the names of any globals found within func"""
    ...

def referredglobals(func, recurse=..., builtin=...): # -> dict_keys[Any | str, Any] | dict_keys[Any, Any]:
    """get the names of objects in the global scope referred to by func"""
    ...

def globalvars(func, recurse=..., builtin=...): # -> dict[Any, Any] | dict[Any | str, Any]:
    """get objects defined in global scope that are referred to by func

    return a dict of {name:object}"""
    ...

def varnames(func): # -> tuple[()] | tuple[tuple[str, ...], tuple[str, ...]]:
    """get names of variables defined by func

    returns a tuple (local vars, local vars referrenced by nested functions)"""
    ...

def baditems(obj, exact=..., safe=...): # -> list[Any | dict[str, Any | dict[str, Any | dict[str, Any | dict[str, Any] | None] | None] | None]] | list[Any]:
    """get items in object that fail to pickle"""
    ...

def badobjects(obj, depth=..., exact=..., safe=...): # -> dict[str, Any | dict[str, Any] | None] | None:
    """get objects that fail to pickle"""
    ...

def badtypes(obj, depth=..., exact=..., safe=...): # -> type[Any] | dict[str, type[Any] | dict[str, Any] | None] | None:
    """get types for objects that fail to pickle"""
    ...

def errors(obj, depth=..., exact=..., safe=...): # -> BaseException | dict[Any, Any] | None:
    """get errors for objects that fail to pickle"""
    ...

