import dtoolconfig
import panda3d.core
from typing import Any, ClassVar

Dtool_PyNativeInterface: int

class BasicSkel(dtoolconfig.DTOOL_SUPER_BASE):
    DtoolClassDict: ClassVar[dict] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getValue(self, *args, **kwargs): ...
    def getValueAlt(self, *args, **kwargs): ...
    def get_value(self, BasicSkelself) -> Any: ...
    def get_value_alt(self, BasicSkelself) -> Any: ...
    def setValue(self, *args, **kwargs): ...
    def setValueAlt(self, *args, **kwargs): ...
    def set_value(self, constBasicSkelself, intn) -> Any: ...
    def set_value_alt(self, constBasicSkelself, intn) -> Any: ...
    def __copy__(self): ...
    def __deepcopy__(self): ...

class TypedSkel(panda3d.core.TypedObject):
    DtoolClassDict: ClassVar[dict] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def getClassType(*args, **kwargs): ...
    def getValue(self, *args, **kwargs): ...
    def getValueAlt(self, *args, **kwargs): ...
    @staticmethod
    def get_class_type() -> Any: ...
    def get_value(self, TypedSkelself) -> Any: ...
    def get_value_alt(self, TypedSkelself) -> Any: ...
    def setValue(self, *args, **kwargs): ...
    def setValueAlt(self, *args, **kwargs): ...
    def set_value(self, constTypedSkelself, intn) -> Any: ...
    def set_value_alt(self, constTypedSkelself, intn) -> Any: ...

def Dtool_BorrowThisReference(*args, **kwargs): ...
